on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
  
    - name: Execute gradle build
      run: ./gradlew build --no-daemon

    - name: Start springboot
      run: |
           chmod +x ./scripts/deploy.sh
           timeout 300s ./scripts/deploy.sh
